# Setup
title:        Jinghua Yuan
tagline:      Assistant Scientist at National Astronomical Observatories, Chinese Academy of Sciences
baseurl:      ""
paginate:     1

# secondary settings
header-img: img/hiGAL.jpg
hmsc-title:    HMSCs--High-mass star starless clumps in the inner Galactic Plane


# About/contact
author:
  name:       Jinghua Yuan
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

#Others
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge